# This file was automatically generated by make import-symbols
# DO NOT MODIFY IT!
# See locale/README.md to know how to import dictionaries

symbols:
🏻	šviesios odos	none
🏼	vidutinio gymio	none
🏽	rusvos odos	none
🏾	tamsios odos	none
🏿	itin tamsios odos	none
℗	garso įrašo autorių teis